services:
  autoannouncements:
    build: .
    image: autoannouncements
    volumes:
      - ./data:/home/app_user/data:ro
    environment:
      AUTO_ANNOUNCEMENTS_PASSWORD: ${AUTO_ANNOUNCEMENTS_PASSWORD:-}
      TZ: ${TZ:-UTC}
    restart: unless-stopped
